import numpy as np
import matplotlib.pyplot as plt
signal1 = np.array([0, 1, 1, 1, 0])
kernel = np.array([0.25, 0.5, 0.25])
image=np.convolve(signal1, kernel, mode='same')
plt.figure(figsize=(12,5))
plt.plot(signal1,label="signal1")
plt.plot(image,label="image")   
plt.xlabel("Sample")
plt.ylabel("Amplitude")
plt.title("Convolution of signal1 with kernel")
plt.grid(True)
plt.legend()
plt.show()
x = np.linspace(0, 2*np.pi, 1000)
y1 = np.sin(x)
y2 = np.sin(5*x)
plt.figure(figsize=(12,5))
plt.plot(x, y1, label="y1")
plt.plot(x, y2, label="y2")
plt.xlabel("x")
plt.ylabel("y")
plt.title("Plot of y1 and y2")
plt.grid(True)
plt.legend()
plt.show()